### ISSUE TITLE
Dependencia LIB libaio1

### ISSUE THREAD

**Issue by raulfdias** [lucasctd/vagrant-oci8-php#1]
Ao rodar o comando ldd /user/lib/php/2013226/oci8.so identificou a falta da lib libaio1. Em alguns casos pode ser necessário instalar com o comando sudo apt-get install libaio1.

**Comment by lucasctd** [comment]
libaio1 já estava no script de instalação do PHP. Algum imprevisto deve ter acontecido durante a instalação.
